*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_CTR_DET_DEP................................*
FORM GET_DATA_ZVSD_CTR_DET_DEP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_CTR_DET_DEP WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_CTR_DET_DEP .
ZVSD_CTR_DET_DEP-CLIENT =
ZTSD_CTR_DET_DEP-CLIENT .
ZVSD_CTR_DET_DEP-AUART =
ZTSD_CTR_DET_DEP-AUART .
ZVSD_CTR_DET_DEP-KUNNR =
ZTSD_CTR_DET_DEP-KUNNR .
ZVSD_CTR_DET_DEP-AUGRU =
ZTSD_CTR_DET_DEP-AUGRU .
ZVSD_CTR_DET_DEP-MATKL =
ZTSD_CTR_DET_DEP-MATKL .
ZVSD_CTR_DET_DEP-BSARK =
ZTSD_CTR_DET_DEP-BSARK .
ZVSD_CTR_DET_DEP-WERKS =
ZTSD_CTR_DET_DEP-WERKS .
ZVSD_CTR_DET_DEP-LGORT =
ZTSD_CTR_DET_DEP-LGORT .
<VIM_TOTAL_STRUC> = ZVSD_CTR_DET_DEP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_CTR_DET_DEP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_CTR_DET_DEP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_CTR_DET_DEP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_CTR_DET_DEP WHERE
  AUART = ZVSD_CTR_DET_DEP-AUART AND
  KUNNR = ZVSD_CTR_DET_DEP-KUNNR AND
  AUGRU = ZVSD_CTR_DET_DEP-AUGRU AND
  MATKL = ZVSD_CTR_DET_DEP-MATKL AND
  BSARK = ZVSD_CTR_DET_DEP-BSARK AND
  WERKS = ZVSD_CTR_DET_DEP-WERKS .
    IF SY-SUBRC = 0.
    DELETE ZTSD_CTR_DET_DEP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_CTR_DET_DEP WHERE
  AUART = ZVSD_CTR_DET_DEP-AUART AND
  KUNNR = ZVSD_CTR_DET_DEP-KUNNR AND
  AUGRU = ZVSD_CTR_DET_DEP-AUGRU AND
  MATKL = ZVSD_CTR_DET_DEP-MATKL AND
  BSARK = ZVSD_CTR_DET_DEP-BSARK AND
  WERKS = ZVSD_CTR_DET_DEP-WERKS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_CTR_DET_DEP.
    ENDIF.
ZTSD_CTR_DET_DEP-CLIENT =
ZVSD_CTR_DET_DEP-CLIENT .
ZTSD_CTR_DET_DEP-AUART =
ZVSD_CTR_DET_DEP-AUART .
ZTSD_CTR_DET_DEP-KUNNR =
ZVSD_CTR_DET_DEP-KUNNR .
ZTSD_CTR_DET_DEP-AUGRU =
ZVSD_CTR_DET_DEP-AUGRU .
ZTSD_CTR_DET_DEP-MATKL =
ZVSD_CTR_DET_DEP-MATKL .
ZTSD_CTR_DET_DEP-BSARK =
ZVSD_CTR_DET_DEP-BSARK .
ZTSD_CTR_DET_DEP-WERKS =
ZVSD_CTR_DET_DEP-WERKS .
ZTSD_CTR_DET_DEP-LGORT =
ZVSD_CTR_DET_DEP-LGORT .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_CTR_DET_DEP ##WARN_OK.
    ELSE.
    INSERT ZTSD_CTR_DET_DEP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_CTR_DET_DEP-UPD_FLAG,
STATUS_ZVSD_CTR_DET_DEP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_CTR_DET_DEP.
  SELECT SINGLE * FROM ZTSD_CTR_DET_DEP WHERE
AUART = ZVSD_CTR_DET_DEP-AUART AND
KUNNR = ZVSD_CTR_DET_DEP-KUNNR AND
AUGRU = ZVSD_CTR_DET_DEP-AUGRU AND
MATKL = ZVSD_CTR_DET_DEP-MATKL AND
BSARK = ZVSD_CTR_DET_DEP-BSARK AND
WERKS = ZVSD_CTR_DET_DEP-WERKS .
ZVSD_CTR_DET_DEP-CLIENT =
ZTSD_CTR_DET_DEP-CLIENT .
ZVSD_CTR_DET_DEP-AUART =
ZTSD_CTR_DET_DEP-AUART .
ZVSD_CTR_DET_DEP-KUNNR =
ZTSD_CTR_DET_DEP-KUNNR .
ZVSD_CTR_DET_DEP-AUGRU =
ZTSD_CTR_DET_DEP-AUGRU .
ZVSD_CTR_DET_DEP-MATKL =
ZTSD_CTR_DET_DEP-MATKL .
ZVSD_CTR_DET_DEP-BSARK =
ZTSD_CTR_DET_DEP-BSARK .
ZVSD_CTR_DET_DEP-WERKS =
ZTSD_CTR_DET_DEP-WERKS .
ZVSD_CTR_DET_DEP-LGORT =
ZTSD_CTR_DET_DEP-LGORT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_CTR_DET_DEP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_CTR_DET_DEP-AUART TO
ZTSD_CTR_DET_DEP-AUART .
MOVE ZVSD_CTR_DET_DEP-KUNNR TO
ZTSD_CTR_DET_DEP-KUNNR .
MOVE ZVSD_CTR_DET_DEP-AUGRU TO
ZTSD_CTR_DET_DEP-AUGRU .
MOVE ZVSD_CTR_DET_DEP-MATKL TO
ZTSD_CTR_DET_DEP-MATKL .
MOVE ZVSD_CTR_DET_DEP-BSARK TO
ZTSD_CTR_DET_DEP-BSARK .
MOVE ZVSD_CTR_DET_DEP-WERKS TO
ZTSD_CTR_DET_DEP-WERKS .
MOVE ZVSD_CTR_DET_DEP-CLIENT TO
ZTSD_CTR_DET_DEP-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_CTR_DET_DEP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_CTR_DET_DEP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_CTR_DET_DEP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
