"Name: \PR:SAPLV60A\FO:USEREXIT_ACCOUNT_PREP_KOMPCV\SE:BEGIN\EI
ENHANCEMENT 0 ZEISD_ACCOUNT_PREP_KOMPCV.
INCLUDE zsdi_gnre_calc_icms_part_save IF FOUND.
kompcv-augru_auft = komkcv-augru.
ENDENHANCEMENT.
