*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVMM_MOV_PARAM..................................*
FORM GET_DATA_ZVMM_MOV_PARAM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTMM_MOV_PARAM WHERE
(VIM_WHERETAB) .
    CLEAR ZVMM_MOV_PARAM .
ZVMM_MOV_PARAM-MANDT =
ZTMM_MOV_PARAM-MANDT .
ZVMM_MOV_PARAM-SHIPFROM =
ZTMM_MOV_PARAM-SHIPFROM .
ZVMM_MOV_PARAM-DIRECAO =
ZTMM_MOV_PARAM-DIRECAO .
ZVMM_MOV_PARAM-CFOP =
ZTMM_MOV_PARAM-CFOP .
ZVMM_MOV_PARAM-MATNR =
ZTMM_MOV_PARAM-MATNR .
ZVMM_MOV_PARAM-MATKL =
ZTMM_MOV_PARAM-MATKL .
ZVMM_MOV_PARAM-TAXLW1 =
ZTMM_MOV_PARAM-TAXLW1 .
ZVMM_MOV_PARAM-TAXLW2 =
ZTMM_MOV_PARAM-TAXLW2 .
ZVMM_MOV_PARAM-TAXLW5 =
ZTMM_MOV_PARAM-TAXLW5 .
ZVMM_MOV_PARAM-TAXLW4 =
ZTMM_MOV_PARAM-TAXLW4 .
ZVMM_MOV_PARAM-TAXSIT =
ZTMM_MOV_PARAM-TAXSIT .
ZVMM_MOV_PARAM-ATIVO =
ZTMM_MOV_PARAM-ATIVO .
<VIM_TOTAL_STRUC> = ZVMM_MOV_PARAM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVMM_MOV_PARAM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVMM_MOV_PARAM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVMM_MOV_PARAM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTMM_MOV_PARAM WHERE
  SHIPFROM = ZVMM_MOV_PARAM-SHIPFROM AND
  DIRECAO = ZVMM_MOV_PARAM-DIRECAO AND
  CFOP = ZVMM_MOV_PARAM-CFOP AND
  MATNR = ZVMM_MOV_PARAM-MATNR AND
  MATKL = ZVMM_MOV_PARAM-MATKL AND
  TAXLW1 = ZVMM_MOV_PARAM-TAXLW1 AND
  TAXLW2 = ZVMM_MOV_PARAM-TAXLW2 AND
  TAXLW5 = ZVMM_MOV_PARAM-TAXLW5 AND
  TAXLW4 = ZVMM_MOV_PARAM-TAXLW4 AND
  TAXSIT = ZVMM_MOV_PARAM-TAXSIT .
    IF SY-SUBRC = 0.
    DELETE ZTMM_MOV_PARAM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTMM_MOV_PARAM WHERE
  SHIPFROM = ZVMM_MOV_PARAM-SHIPFROM AND
  DIRECAO = ZVMM_MOV_PARAM-DIRECAO AND
  CFOP = ZVMM_MOV_PARAM-CFOP AND
  MATNR = ZVMM_MOV_PARAM-MATNR AND
  MATKL = ZVMM_MOV_PARAM-MATKL AND
  TAXLW1 = ZVMM_MOV_PARAM-TAXLW1 AND
  TAXLW2 = ZVMM_MOV_PARAM-TAXLW2 AND
  TAXLW5 = ZVMM_MOV_PARAM-TAXLW5 AND
  TAXLW4 = ZVMM_MOV_PARAM-TAXLW4 AND
  TAXSIT = ZVMM_MOV_PARAM-TAXSIT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTMM_MOV_PARAM.
    ENDIF.
ZTMM_MOV_PARAM-MANDT =
ZVMM_MOV_PARAM-MANDT .
ZTMM_MOV_PARAM-SHIPFROM =
ZVMM_MOV_PARAM-SHIPFROM .
ZTMM_MOV_PARAM-DIRECAO =
ZVMM_MOV_PARAM-DIRECAO .
ZTMM_MOV_PARAM-CFOP =
ZVMM_MOV_PARAM-CFOP .
ZTMM_MOV_PARAM-MATNR =
ZVMM_MOV_PARAM-MATNR .
ZTMM_MOV_PARAM-MATKL =
ZVMM_MOV_PARAM-MATKL .
ZTMM_MOV_PARAM-TAXLW1 =
ZVMM_MOV_PARAM-TAXLW1 .
ZTMM_MOV_PARAM-TAXLW2 =
ZVMM_MOV_PARAM-TAXLW2 .
ZTMM_MOV_PARAM-TAXLW5 =
ZVMM_MOV_PARAM-TAXLW5 .
ZTMM_MOV_PARAM-TAXLW4 =
ZVMM_MOV_PARAM-TAXLW4 .
ZTMM_MOV_PARAM-TAXSIT =
ZVMM_MOV_PARAM-TAXSIT .
ZTMM_MOV_PARAM-ATIVO =
ZVMM_MOV_PARAM-ATIVO .
    IF SY-SUBRC = 0.
    UPDATE ZTMM_MOV_PARAM ##WARN_OK.
    ELSE.
    INSERT ZTMM_MOV_PARAM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVMM_MOV_PARAM-UPD_FLAG,
STATUS_ZVMM_MOV_PARAM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVMM_MOV_PARAM.
  SELECT SINGLE * FROM ZTMM_MOV_PARAM WHERE
SHIPFROM = ZVMM_MOV_PARAM-SHIPFROM AND
DIRECAO = ZVMM_MOV_PARAM-DIRECAO AND
CFOP = ZVMM_MOV_PARAM-CFOP AND
MATNR = ZVMM_MOV_PARAM-MATNR AND
MATKL = ZVMM_MOV_PARAM-MATKL AND
TAXLW1 = ZVMM_MOV_PARAM-TAXLW1 AND
TAXLW2 = ZVMM_MOV_PARAM-TAXLW2 AND
TAXLW5 = ZVMM_MOV_PARAM-TAXLW5 AND
TAXLW4 = ZVMM_MOV_PARAM-TAXLW4 AND
TAXSIT = ZVMM_MOV_PARAM-TAXSIT .
ZVMM_MOV_PARAM-MANDT =
ZTMM_MOV_PARAM-MANDT .
ZVMM_MOV_PARAM-SHIPFROM =
ZTMM_MOV_PARAM-SHIPFROM .
ZVMM_MOV_PARAM-DIRECAO =
ZTMM_MOV_PARAM-DIRECAO .
ZVMM_MOV_PARAM-CFOP =
ZTMM_MOV_PARAM-CFOP .
ZVMM_MOV_PARAM-MATNR =
ZTMM_MOV_PARAM-MATNR .
ZVMM_MOV_PARAM-MATKL =
ZTMM_MOV_PARAM-MATKL .
ZVMM_MOV_PARAM-TAXLW1 =
ZTMM_MOV_PARAM-TAXLW1 .
ZVMM_MOV_PARAM-TAXLW2 =
ZTMM_MOV_PARAM-TAXLW2 .
ZVMM_MOV_PARAM-TAXLW5 =
ZTMM_MOV_PARAM-TAXLW5 .
ZVMM_MOV_PARAM-TAXLW4 =
ZTMM_MOV_PARAM-TAXLW4 .
ZVMM_MOV_PARAM-TAXSIT =
ZTMM_MOV_PARAM-TAXSIT .
ZVMM_MOV_PARAM-ATIVO =
ZTMM_MOV_PARAM-ATIVO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVMM_MOV_PARAM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVMM_MOV_PARAM-SHIPFROM TO
ZTMM_MOV_PARAM-SHIPFROM .
MOVE ZVMM_MOV_PARAM-DIRECAO TO
ZTMM_MOV_PARAM-DIRECAO .
MOVE ZVMM_MOV_PARAM-CFOP TO
ZTMM_MOV_PARAM-CFOP .
MOVE ZVMM_MOV_PARAM-MATNR TO
ZTMM_MOV_PARAM-MATNR .
MOVE ZVMM_MOV_PARAM-MATKL TO
ZTMM_MOV_PARAM-MATKL .
MOVE ZVMM_MOV_PARAM-TAXLW1 TO
ZTMM_MOV_PARAM-TAXLW1 .
MOVE ZVMM_MOV_PARAM-TAXLW2 TO
ZTMM_MOV_PARAM-TAXLW2 .
MOVE ZVMM_MOV_PARAM-TAXLW5 TO
ZTMM_MOV_PARAM-TAXLW5 .
MOVE ZVMM_MOV_PARAM-TAXLW4 TO
ZTMM_MOV_PARAM-TAXLW4 .
MOVE ZVMM_MOV_PARAM-TAXSIT TO
ZTMM_MOV_PARAM-TAXSIT .
MOVE ZVMM_MOV_PARAM-MANDT TO
ZTMM_MOV_PARAM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTMM_MOV_PARAM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTMM_MOV_PARAM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTMM_MOV_PARAM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
