*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_MATERIAL...................................*
FORM GET_DATA_ZVSD_MATERIAL.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_MATERIAL WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_MATERIAL .
ZVSD_MATERIAL-CLIENT =
ZTSD_MATERIAL-CLIENT .
ZVSD_MATERIAL-CENTRO =
ZTSD_MATERIAL-CENTRO .
ZVSD_MATERIAL-UF =
ZTSD_MATERIAL-UF .
ZVSD_MATERIAL-MATERIAL =
ZTSD_MATERIAL-MATERIAL .
ZVSD_MATERIAL-DESCRICAO =
ZTSD_MATERIAL-DESCRICAO .
ZVSD_MATERIAL-AGREGADO =
ZTSD_MATERIAL-AGREGADO .
ZVSD_MATERIAL-ICMS_DEST =
ZTSD_MATERIAL-ICMS_DEST .
ZVSD_MATERIAL-ICMS_ORIG =
ZTSD_MATERIAL-ICMS_ORIG .
ZVSD_MATERIAL-COMPRA_INTERNA =
ZTSD_MATERIAL-COMPRA_INTERNA .
ZVSD_MATERIAL-BASE_RED_ORIG =
ZTSD_MATERIAL-BASE_RED_ORIG .
ZVSD_MATERIAL-BASE_RED_DEST =
ZTSD_MATERIAL-BASE_RED_DEST .
ZVSD_MATERIAL-TAXA_FCP =
ZTSD_MATERIAL-TAXA_FCP .
ZVSD_MATERIAL-ICMS_EFET =
ZTSD_MATERIAL-ICMS_EFET .
ZVSD_MATERIAL-BASEREDEFET =
ZTSD_MATERIAL-BASEREDEFET .
ZVSD_MATERIAL-PRECO_COMPAR =
ZTSD_MATERIAL-PRECO_COMPAR .
ZVSD_MATERIAL-PRECO_PAUTA =
ZTSD_MATERIAL-PRECO_PAUTA .
ZVSD_MATERIAL-AGREGADO_PAUTA =
ZTSD_MATERIAL-AGREGADO_PAUTA .
ZVSD_MATERIAL-NRO_UNIDS =
ZTSD_MATERIAL-NRO_UNIDS .
ZVSD_MATERIAL-UM =
ZTSD_MATERIAL-UM .
ZVSD_MATERIAL-MODALIDADE =
ZTSD_MATERIAL-MODALIDADE .
ZVSD_MATERIAL-CALC_EFETIVO =
ZTSD_MATERIAL-CALC_EFETIVO .
ZVSD_MATERIAL-PERC_BC_ICMS =
ZTSD_MATERIAL-PERC_BC_ICMS .
<VIM_TOTAL_STRUC> = ZVSD_MATERIAL.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_MATERIAL .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_MATERIAL.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_MATERIAL-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_MATERIAL WHERE
  CENTRO = ZVSD_MATERIAL-CENTRO AND
  UF = ZVSD_MATERIAL-UF AND
  MATERIAL = ZVSD_MATERIAL-MATERIAL .
    IF SY-SUBRC = 0.
    DELETE ZTSD_MATERIAL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_MATERIAL WHERE
  CENTRO = ZVSD_MATERIAL-CENTRO AND
  UF = ZVSD_MATERIAL-UF AND
  MATERIAL = ZVSD_MATERIAL-MATERIAL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_MATERIAL.
    ENDIF.
ZTSD_MATERIAL-CLIENT =
ZVSD_MATERIAL-CLIENT .
ZTSD_MATERIAL-CENTRO =
ZVSD_MATERIAL-CENTRO .
ZTSD_MATERIAL-UF =
ZVSD_MATERIAL-UF .
ZTSD_MATERIAL-MATERIAL =
ZVSD_MATERIAL-MATERIAL .
ZTSD_MATERIAL-DESCRICAO =
ZVSD_MATERIAL-DESCRICAO .
ZTSD_MATERIAL-AGREGADO =
ZVSD_MATERIAL-AGREGADO .
ZTSD_MATERIAL-ICMS_DEST =
ZVSD_MATERIAL-ICMS_DEST .
ZTSD_MATERIAL-ICMS_ORIG =
ZVSD_MATERIAL-ICMS_ORIG .
ZTSD_MATERIAL-COMPRA_INTERNA =
ZVSD_MATERIAL-COMPRA_INTERNA .
ZTSD_MATERIAL-BASE_RED_ORIG =
ZVSD_MATERIAL-BASE_RED_ORIG .
ZTSD_MATERIAL-BASE_RED_DEST =
ZVSD_MATERIAL-BASE_RED_DEST .
ZTSD_MATERIAL-TAXA_FCP =
ZVSD_MATERIAL-TAXA_FCP .
ZTSD_MATERIAL-ICMS_EFET =
ZVSD_MATERIAL-ICMS_EFET .
ZTSD_MATERIAL-BASEREDEFET =
ZVSD_MATERIAL-BASEREDEFET .
ZTSD_MATERIAL-PRECO_COMPAR =
ZVSD_MATERIAL-PRECO_COMPAR .
ZTSD_MATERIAL-PRECO_PAUTA =
ZVSD_MATERIAL-PRECO_PAUTA .
ZTSD_MATERIAL-AGREGADO_PAUTA =
ZVSD_MATERIAL-AGREGADO_PAUTA .
ZTSD_MATERIAL-NRO_UNIDS =
ZVSD_MATERIAL-NRO_UNIDS .
ZTSD_MATERIAL-UM =
ZVSD_MATERIAL-UM .
ZTSD_MATERIAL-MODALIDADE =
ZVSD_MATERIAL-MODALIDADE .
ZTSD_MATERIAL-CALC_EFETIVO =
ZVSD_MATERIAL-CALC_EFETIVO .
ZTSD_MATERIAL-PERC_BC_ICMS =
ZVSD_MATERIAL-PERC_BC_ICMS .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_MATERIAL ##WARN_OK.
    ELSE.
    INSERT ZTSD_MATERIAL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_MATERIAL-UPD_FLAG,
STATUS_ZVSD_MATERIAL-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_MATERIAL.
  SELECT SINGLE * FROM ZTSD_MATERIAL WHERE
CENTRO = ZVSD_MATERIAL-CENTRO AND
UF = ZVSD_MATERIAL-UF AND
MATERIAL = ZVSD_MATERIAL-MATERIAL .
ZVSD_MATERIAL-CLIENT =
ZTSD_MATERIAL-CLIENT .
ZVSD_MATERIAL-CENTRO =
ZTSD_MATERIAL-CENTRO .
ZVSD_MATERIAL-UF =
ZTSD_MATERIAL-UF .
ZVSD_MATERIAL-MATERIAL =
ZTSD_MATERIAL-MATERIAL .
ZVSD_MATERIAL-DESCRICAO =
ZTSD_MATERIAL-DESCRICAO .
ZVSD_MATERIAL-AGREGADO =
ZTSD_MATERIAL-AGREGADO .
ZVSD_MATERIAL-ICMS_DEST =
ZTSD_MATERIAL-ICMS_DEST .
ZVSD_MATERIAL-ICMS_ORIG =
ZTSD_MATERIAL-ICMS_ORIG .
ZVSD_MATERIAL-COMPRA_INTERNA =
ZTSD_MATERIAL-COMPRA_INTERNA .
ZVSD_MATERIAL-BASE_RED_ORIG =
ZTSD_MATERIAL-BASE_RED_ORIG .
ZVSD_MATERIAL-BASE_RED_DEST =
ZTSD_MATERIAL-BASE_RED_DEST .
ZVSD_MATERIAL-TAXA_FCP =
ZTSD_MATERIAL-TAXA_FCP .
ZVSD_MATERIAL-ICMS_EFET =
ZTSD_MATERIAL-ICMS_EFET .
ZVSD_MATERIAL-BASEREDEFET =
ZTSD_MATERIAL-BASEREDEFET .
ZVSD_MATERIAL-PRECO_COMPAR =
ZTSD_MATERIAL-PRECO_COMPAR .
ZVSD_MATERIAL-PRECO_PAUTA =
ZTSD_MATERIAL-PRECO_PAUTA .
ZVSD_MATERIAL-AGREGADO_PAUTA =
ZTSD_MATERIAL-AGREGADO_PAUTA .
ZVSD_MATERIAL-NRO_UNIDS =
ZTSD_MATERIAL-NRO_UNIDS .
ZVSD_MATERIAL-UM =
ZTSD_MATERIAL-UM .
ZVSD_MATERIAL-MODALIDADE =
ZTSD_MATERIAL-MODALIDADE .
ZVSD_MATERIAL-CALC_EFETIVO =
ZTSD_MATERIAL-CALC_EFETIVO .
ZVSD_MATERIAL-PERC_BC_ICMS =
ZTSD_MATERIAL-PERC_BC_ICMS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_MATERIAL USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_MATERIAL-CENTRO TO
ZTSD_MATERIAL-CENTRO .
MOVE ZVSD_MATERIAL-UF TO
ZTSD_MATERIAL-UF .
MOVE ZVSD_MATERIAL-MATERIAL TO
ZTSD_MATERIAL-MATERIAL .
MOVE ZVSD_MATERIAL-CLIENT TO
ZTSD_MATERIAL-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_MATERIAL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_MATERIAL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_MATERIAL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
