*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_PIS_COFINS.................................*
FORM GET_DATA_ZVSD_PIS_COFINS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_PIS_COFINS WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_PIS_COFINS .
ZVSD_PIS_COFINS-CLIENT =
ZTSD_PIS_COFINS-CLIENT .
ZVSD_PIS_COFINS-WERKS =
ZTSD_PIS_COFINS-WERKS .
ZVSD_PIS_COFINS-BRSCH =
ZTSD_PIS_COFINS-BRSCH .
ZVSD_PIS_COFINS-TDT =
ZTSD_PIS_COFINS-TDT .
ZVSD_PIS_COFINS-MATKL =
ZTSD_PIS_COFINS-MATKL .
<VIM_TOTAL_STRUC> = ZVSD_PIS_COFINS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_PIS_COFINS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_PIS_COFINS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_PIS_COFINS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_PIS_COFINS WHERE
  WERKS = ZVSD_PIS_COFINS-WERKS AND
  BRSCH = ZVSD_PIS_COFINS-BRSCH AND
  TDT = ZVSD_PIS_COFINS-TDT AND
  MATKL = ZVSD_PIS_COFINS-MATKL .
    IF SY-SUBRC = 0.
    DELETE ZTSD_PIS_COFINS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_PIS_COFINS WHERE
  WERKS = ZVSD_PIS_COFINS-WERKS AND
  BRSCH = ZVSD_PIS_COFINS-BRSCH AND
  TDT = ZVSD_PIS_COFINS-TDT AND
  MATKL = ZVSD_PIS_COFINS-MATKL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_PIS_COFINS.
    ENDIF.
ZTSD_PIS_COFINS-CLIENT =
ZVSD_PIS_COFINS-CLIENT .
ZTSD_PIS_COFINS-WERKS =
ZVSD_PIS_COFINS-WERKS .
ZTSD_PIS_COFINS-BRSCH =
ZVSD_PIS_COFINS-BRSCH .
ZTSD_PIS_COFINS-TDT =
ZVSD_PIS_COFINS-TDT .
ZTSD_PIS_COFINS-MATKL =
ZVSD_PIS_COFINS-MATKL .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_PIS_COFINS ##WARN_OK.
    ELSE.
    INSERT ZTSD_PIS_COFINS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_PIS_COFINS-UPD_FLAG,
STATUS_ZVSD_PIS_COFINS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_PIS_COFINS.
  SELECT SINGLE * FROM ZTSD_PIS_COFINS WHERE
WERKS = ZVSD_PIS_COFINS-WERKS AND
BRSCH = ZVSD_PIS_COFINS-BRSCH AND
TDT = ZVSD_PIS_COFINS-TDT AND
MATKL = ZVSD_PIS_COFINS-MATKL .
ZVSD_PIS_COFINS-CLIENT =
ZTSD_PIS_COFINS-CLIENT .
ZVSD_PIS_COFINS-WERKS =
ZTSD_PIS_COFINS-WERKS .
ZVSD_PIS_COFINS-BRSCH =
ZTSD_PIS_COFINS-BRSCH .
ZVSD_PIS_COFINS-TDT =
ZTSD_PIS_COFINS-TDT .
ZVSD_PIS_COFINS-MATKL =
ZTSD_PIS_COFINS-MATKL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_PIS_COFINS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_PIS_COFINS-WERKS TO
ZTSD_PIS_COFINS-WERKS .
MOVE ZVSD_PIS_COFINS-BRSCH TO
ZTSD_PIS_COFINS-BRSCH .
MOVE ZVSD_PIS_COFINS-TDT TO
ZTSD_PIS_COFINS-TDT .
MOVE ZVSD_PIS_COFINS-MATKL TO
ZTSD_PIS_COFINS-MATKL .
MOVE ZVSD_PIS_COFINS-CLIENT TO
ZTSD_PIS_COFINS-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_PIS_COFINS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_PIS_COFINS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_PIS_COFINS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
