*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_GNRET020...................................*
FORM GET_DATA_ZVSD_GNRET020.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_GNRET020 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_GNRET020 .
ZVSD_GNRET020-MANDT =
ZTSD_GNRET020-MANDT .
ZVSD_GNRET020-REGIAO_ORIGEM =
ZTSD_GNRET020-REGIAO_ORIGEM .
ZVSD_GNRET020-REGIAO_DESTINO =
ZTSD_GNRET020-REGIAO_DESTINO .
ZVSD_GNRET020-NCM =
ZTSD_GNRET020-NCM .
ZVSD_GNRET020-TIPO_GUIA =
ZTSD_GNRET020-TIPO_GUIA .
ZVSD_GNRET020-MODO_EXECUCAO =
ZTSD_GNRET020-MODO_EXECUCAO .
ZVSD_GNRET020-VALOR_FIXO =
ZTSD_GNRET020-VALOR_FIXO .
<VIM_TOTAL_STRUC> = ZVSD_GNRET020.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_GNRET020 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_GNRET020.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_GNRET020-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET020 WHERE
  REGIAO_ORIGEM = ZVSD_GNRET020-REGIAO_ORIGEM AND
  REGIAO_DESTINO = ZVSD_GNRET020-REGIAO_DESTINO .
    IF SY-SUBRC = 0.
    DELETE ZTSD_GNRET020 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET020 WHERE
  REGIAO_ORIGEM = ZVSD_GNRET020-REGIAO_ORIGEM AND
  REGIAO_DESTINO = ZVSD_GNRET020-REGIAO_DESTINO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_GNRET020.
    ENDIF.
ZTSD_GNRET020-MANDT =
ZVSD_GNRET020-MANDT .
ZTSD_GNRET020-REGIAO_ORIGEM =
ZVSD_GNRET020-REGIAO_ORIGEM .
ZTSD_GNRET020-REGIAO_DESTINO =
ZVSD_GNRET020-REGIAO_DESTINO .
ZTSD_GNRET020-NCM =
ZVSD_GNRET020-NCM .
ZTSD_GNRET020-TIPO_GUIA =
ZVSD_GNRET020-TIPO_GUIA .
ZTSD_GNRET020-MODO_EXECUCAO =
ZVSD_GNRET020-MODO_EXECUCAO .
ZTSD_GNRET020-VALOR_FIXO =
ZVSD_GNRET020-VALOR_FIXO .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_GNRET020 ##WARN_OK.
    ELSE.
    INSERT ZTSD_GNRET020 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_GNRET020-UPD_FLAG,
STATUS_ZVSD_GNRET020-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_GNRET020.
  SELECT SINGLE * FROM ZTSD_GNRET020 WHERE
REGIAO_ORIGEM = ZVSD_GNRET020-REGIAO_ORIGEM AND
REGIAO_DESTINO = ZVSD_GNRET020-REGIAO_DESTINO .
ZVSD_GNRET020-MANDT =
ZTSD_GNRET020-MANDT .
ZVSD_GNRET020-REGIAO_ORIGEM =
ZTSD_GNRET020-REGIAO_ORIGEM .
ZVSD_GNRET020-REGIAO_DESTINO =
ZTSD_GNRET020-REGIAO_DESTINO .
ZVSD_GNRET020-NCM =
ZTSD_GNRET020-NCM .
ZVSD_GNRET020-TIPO_GUIA =
ZTSD_GNRET020-TIPO_GUIA .
ZVSD_GNRET020-MODO_EXECUCAO =
ZTSD_GNRET020-MODO_EXECUCAO .
ZVSD_GNRET020-VALOR_FIXO =
ZTSD_GNRET020-VALOR_FIXO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_GNRET020 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_GNRET020-REGIAO_ORIGEM TO
ZTSD_GNRET020-REGIAO_ORIGEM .
MOVE ZVSD_GNRET020-REGIAO_DESTINO TO
ZTSD_GNRET020-REGIAO_DESTINO .
MOVE ZVSD_GNRET020-MANDT TO
ZTSD_GNRET020-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_GNRET020'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_GNRET020 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_GNRET020'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
