*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_GNRET005...................................*
FORM GET_DATA_ZVSD_GNRET005.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_GNRET005 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_GNRET005 .
ZVSD_GNRET005-MANDT =
ZTSD_GNRET005-MANDT .
ZVSD_GNRET005-SHIPFROM =
ZTSD_GNRET005-SHIPFROM .
ZVSD_GNRET005-SHIPTO =
ZTSD_GNRET005-SHIPTO .
ZVSD_GNRET005-CONSUMO =
ZTSD_GNRET005-CONSUMO .
ZVSD_GNRET005-TPGUIA =
ZTSD_GNRET005-TPGUIA .
ZVSD_GNRET005-MODO =
ZTSD_GNRET005-MODO .
ZVSD_GNRET005-GUIA_POR_RECEITA =
ZTSD_GNRET005-GUIA_POR_RECEITA .
ZVSD_GNRET005-ZSUB =
ZTSD_GNRET005-ZSUB .
ZVSD_GNRET005-APURACAO =
ZTSD_GNRET005-APURACAO .
ZVSD_GNRET005-DESTINO =
ZTSD_GNRET005-DESTINO .
<VIM_TOTAL_STRUC> = ZVSD_GNRET005.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_GNRET005 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_GNRET005.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_GNRET005-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET005 WHERE
  SHIPFROM = ZVSD_GNRET005-SHIPFROM AND
  SHIPTO = ZVSD_GNRET005-SHIPTO AND
  CONSUMO = ZVSD_GNRET005-CONSUMO .
    IF SY-SUBRC = 0.
    DELETE ZTSD_GNRET005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET005 WHERE
  SHIPFROM = ZVSD_GNRET005-SHIPFROM AND
  SHIPTO = ZVSD_GNRET005-SHIPTO AND
  CONSUMO = ZVSD_GNRET005-CONSUMO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_GNRET005.
    ENDIF.
ZTSD_GNRET005-MANDT =
ZVSD_GNRET005-MANDT .
ZTSD_GNRET005-SHIPFROM =
ZVSD_GNRET005-SHIPFROM .
ZTSD_GNRET005-SHIPTO =
ZVSD_GNRET005-SHIPTO .
ZTSD_GNRET005-CONSUMO =
ZVSD_GNRET005-CONSUMO .
ZTSD_GNRET005-TPGUIA =
ZVSD_GNRET005-TPGUIA .
ZTSD_GNRET005-MODO =
ZVSD_GNRET005-MODO .
ZTSD_GNRET005-GUIA_POR_RECEITA =
ZVSD_GNRET005-GUIA_POR_RECEITA .
ZTSD_GNRET005-ZSUB =
ZVSD_GNRET005-ZSUB .
ZTSD_GNRET005-APURACAO =
ZVSD_GNRET005-APURACAO .
ZTSD_GNRET005-DESTINO =
ZVSD_GNRET005-DESTINO .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_GNRET005 ##WARN_OK.
    ELSE.
    INSERT ZTSD_GNRET005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_GNRET005-UPD_FLAG,
STATUS_ZVSD_GNRET005-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_GNRET005.
  SELECT SINGLE * FROM ZTSD_GNRET005 WHERE
SHIPFROM = ZVSD_GNRET005-SHIPFROM AND
SHIPTO = ZVSD_GNRET005-SHIPTO AND
CONSUMO = ZVSD_GNRET005-CONSUMO .
ZVSD_GNRET005-MANDT =
ZTSD_GNRET005-MANDT .
ZVSD_GNRET005-SHIPFROM =
ZTSD_GNRET005-SHIPFROM .
ZVSD_GNRET005-SHIPTO =
ZTSD_GNRET005-SHIPTO .
ZVSD_GNRET005-CONSUMO =
ZTSD_GNRET005-CONSUMO .
ZVSD_GNRET005-TPGUIA =
ZTSD_GNRET005-TPGUIA .
ZVSD_GNRET005-MODO =
ZTSD_GNRET005-MODO .
ZVSD_GNRET005-GUIA_POR_RECEITA =
ZTSD_GNRET005-GUIA_POR_RECEITA .
ZVSD_GNRET005-ZSUB =
ZTSD_GNRET005-ZSUB .
ZVSD_GNRET005-APURACAO =
ZTSD_GNRET005-APURACAO .
ZVSD_GNRET005-DESTINO =
ZTSD_GNRET005-DESTINO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_GNRET005 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_GNRET005-SHIPFROM TO
ZTSD_GNRET005-SHIPFROM .
MOVE ZVSD_GNRET005-SHIPTO TO
ZTSD_GNRET005-SHIPTO .
MOVE ZVSD_GNRET005-CONSUMO TO
ZTSD_GNRET005-CONSUMO .
MOVE ZVSD_GNRET005-MANDT TO
ZTSD_GNRET005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_GNRET005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_GNRET005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_GNRET005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
