*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_GNRET008...................................*
FORM GET_DATA_ZVSD_GNRET008.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_GNRET008 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_GNRET008 .
ZVSD_GNRET008-MANDT =
ZTSD_GNRET008-MANDT .
ZVSD_GNRET008-NFTYPE =
ZTSD_GNRET008-NFTYPE .
ZVSD_GNRET008-CFOP =
ZTSD_GNRET008-CFOP .
    SELECT SINGLE * FROM J_1BAA WHERE
NFTYPE = ZTSD_GNRET008-NFTYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM J_1BAAT WHERE
NFTYPE = J_1BAA-NFTYPE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVSD_GNRET008-NFTTXT =
J_1BAAT-NFTTXT .
      ENDIF.
    ENDIF.
    SELECT * FROM J_1BAGN WHERE
CFOP = ZTSD_GNRET008-CFOP .
      SELECT SINGLE * FROM J_1BAGNT WHERE
VERSION = J_1BAGN-VERSION AND
CFOP = J_1BAGN-CFOP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVSD_GNRET008-CFOTXT =
J_1BAGNT-CFOTXT .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZVSD_GNRET008.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_GNRET008 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_GNRET008.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_GNRET008-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET008 WHERE
  NFTYPE = ZVSD_GNRET008-NFTYPE AND
  CFOP = ZVSD_GNRET008-CFOP .
    IF SY-SUBRC = 0.
    DELETE ZTSD_GNRET008 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET008 WHERE
  NFTYPE = ZVSD_GNRET008-NFTYPE AND
  CFOP = ZVSD_GNRET008-CFOP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_GNRET008.
    ENDIF.
ZTSD_GNRET008-MANDT =
ZVSD_GNRET008-MANDT .
ZTSD_GNRET008-NFTYPE =
ZVSD_GNRET008-NFTYPE .
ZTSD_GNRET008-CFOP =
ZVSD_GNRET008-CFOP .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_GNRET008 ##WARN_OK.
    ELSE.
    INSERT ZTSD_GNRET008 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_GNRET008-UPD_FLAG,
STATUS_ZVSD_GNRET008-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_GNRET008.
  SELECT SINGLE * FROM ZTSD_GNRET008 WHERE
NFTYPE = ZVSD_GNRET008-NFTYPE AND
CFOP = ZVSD_GNRET008-CFOP .
ZVSD_GNRET008-MANDT =
ZTSD_GNRET008-MANDT .
ZVSD_GNRET008-NFTYPE =
ZTSD_GNRET008-NFTYPE .
ZVSD_GNRET008-CFOP =
ZTSD_GNRET008-CFOP .
    SELECT SINGLE * FROM J_1BAA WHERE
NFTYPE = ZTSD_GNRET008-NFTYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM J_1BAAT WHERE
NFTYPE = J_1BAA-NFTYPE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVSD_GNRET008-NFTTXT =
J_1BAAT-NFTTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVSD_GNRET008-NFTTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVSD_GNRET008-NFTTXT .
    ENDIF.
    SELECT * FROM J_1BAGN WHERE
CFOP = ZTSD_GNRET008-CFOP .
      SELECT SINGLE * FROM J_1BAGNT WHERE
VERSION = J_1BAGN-VERSION AND
CFOP = J_1BAGN-CFOP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVSD_GNRET008-CFOTXT =
J_1BAGNT-CFOTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVSD_GNRET008-CFOTXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZVSD_GNRET008-CFOTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_GNRET008 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_GNRET008-NFTYPE TO
ZTSD_GNRET008-NFTYPE .
MOVE ZVSD_GNRET008-CFOP TO
ZTSD_GNRET008-CFOP .
MOVE ZVSD_GNRET008-MANDT TO
ZTSD_GNRET008-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_GNRET008'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_GNRET008 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_GNRET008'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVSD_GNRET008 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTSD_GNRET008-MANDT =
ZVSD_GNRET008-MANDT .
ZTSD_GNRET008-NFTYPE =
ZVSD_GNRET008-NFTYPE .
ZTSD_GNRET008-CFOP =
ZVSD_GNRET008-CFOP .
    SELECT SINGLE * FROM J_1BAA WHERE
NFTYPE = ZTSD_GNRET008-NFTYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM J_1BAAT WHERE
NFTYPE = J_1BAA-NFTYPE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVSD_GNRET008-NFTTXT =
J_1BAAT-NFTTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVSD_GNRET008-NFTTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVSD_GNRET008-NFTTXT .
    ENDIF.
    SELECT * FROM J_1BAGN WHERE
CFOP = ZTSD_GNRET008-CFOP .
      SELECT SINGLE * FROM J_1BAGNT WHERE
VERSION = J_1BAGN-VERSION AND
CFOP = J_1BAGN-CFOP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVSD_GNRET008-CFOTXT =
J_1BAGNT-CFOTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVSD_GNRET008-CFOTXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZVSD_GNRET008-CFOTXT .
    ENDIF.
ENDFORM.
