*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_IPI........................................*
FORM GET_DATA_ZVSD_IPI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_IPI WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_IPI .
ZVSD_IPI-CLIENT =
ZTSD_IPI-CLIENT .
ZVSD_IPI-WERKS =
ZTSD_IPI-WERKS .
ZVSD_IPI-TXJCD =
ZTSD_IPI-TXJCD .
ZVSD_IPI-BRSCH =
ZTSD_IPI-BRSCH .
ZVSD_IPI-MATKL =
ZTSD_IPI-MATKL .
ZVSD_IPI-TAXLAW =
ZTSD_IPI-TAXLAW .
<VIM_TOTAL_STRUC> = ZVSD_IPI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_IPI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_IPI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_IPI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_IPI WHERE
  WERKS = ZVSD_IPI-WERKS AND
  TXJCD = ZVSD_IPI-TXJCD AND
  BRSCH = ZVSD_IPI-BRSCH AND
  MATKL = ZVSD_IPI-MATKL .
    IF SY-SUBRC = 0.
    DELETE ZTSD_IPI .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_IPI WHERE
  WERKS = ZVSD_IPI-WERKS AND
  TXJCD = ZVSD_IPI-TXJCD AND
  BRSCH = ZVSD_IPI-BRSCH AND
  MATKL = ZVSD_IPI-MATKL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_IPI.
    ENDIF.
ZTSD_IPI-CLIENT =
ZVSD_IPI-CLIENT .
ZTSD_IPI-WERKS =
ZVSD_IPI-WERKS .
ZTSD_IPI-TXJCD =
ZVSD_IPI-TXJCD .
ZTSD_IPI-BRSCH =
ZVSD_IPI-BRSCH .
ZTSD_IPI-MATKL =
ZVSD_IPI-MATKL .
ZTSD_IPI-TAXLAW =
ZVSD_IPI-TAXLAW .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_IPI ##WARN_OK.
    ELSE.
    INSERT ZTSD_IPI .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_IPI-UPD_FLAG,
STATUS_ZVSD_IPI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVSD_IPI.
  SELECT SINGLE * FROM ZTSD_IPI WHERE
WERKS = ZVSD_IPI-WERKS AND
TXJCD = ZVSD_IPI-TXJCD AND
BRSCH = ZVSD_IPI-BRSCH AND
MATKL = ZVSD_IPI-MATKL .
ZVSD_IPI-CLIENT =
ZTSD_IPI-CLIENT .
ZVSD_IPI-WERKS =
ZTSD_IPI-WERKS .
ZVSD_IPI-TXJCD =
ZTSD_IPI-TXJCD .
ZVSD_IPI-BRSCH =
ZTSD_IPI-BRSCH .
ZVSD_IPI-MATKL =
ZTSD_IPI-MATKL .
ZVSD_IPI-TAXLAW =
ZTSD_IPI-TAXLAW .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_IPI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_IPI-WERKS TO
ZTSD_IPI-WERKS .
MOVE ZVSD_IPI-TXJCD TO
ZTSD_IPI-TXJCD .
MOVE ZVSD_IPI-BRSCH TO
ZTSD_IPI-BRSCH .
MOVE ZVSD_IPI-MATKL TO
ZTSD_IPI-MATKL .
MOVE ZVSD_IPI-CLIENT TO
ZTSD_IPI-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_IPI'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_IPI TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_IPI'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
