*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_GNRET009...................................*
FORM GET_DATA_ZVSD_GNRET009.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_GNRET009 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_GNRET009 .
ZVSD_GNRET009-MANDT =
ZTSD_GNRET009-MANDT .
ZVSD_GNRET009-BUKRS =
ZTSD_GNRET009-BUKRS .
ZVSD_GNRET009-BRANCH =
ZTSD_GNRET009-BRANCH .
ZVSD_GNRET009-SHIPTO =
ZTSD_GNRET009-SHIPTO .
ZVSD_GNRET009-TAXTYP =
ZTSD_GNRET009-TAXTYP .
ZVSD_GNRET009-ZSUB =
ZTSD_GNRET009-ZSUB .
ZVSD_GNRET009-ADIANTAMENTO =
ZTSD_GNRET009-ADIANTAMENTO .
ZVSD_GNRET009-LIFNR =
ZTSD_GNRET009-LIFNR .
ZVSD_GNRET009-HKONT =
ZTSD_GNRET009-HKONT .
ZVSD_GNRET009-HBKID =
ZTSD_GNRET009-HBKID .
<VIM_TOTAL_STRUC> = ZVSD_GNRET009.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_GNRET009 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_GNRET009.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_GNRET009-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET009 WHERE
  BUKRS = ZVSD_GNRET009-BUKRS AND
  BRANCH = ZVSD_GNRET009-BRANCH AND
  SHIPTO = ZVSD_GNRET009-SHIPTO AND
  TAXTYP = ZVSD_GNRET009-TAXTYP AND
  ZSUB = ZVSD_GNRET009-ZSUB AND
  ADIANTAMENTO = ZVSD_GNRET009-ADIANTAMENTO .
    IF SY-SUBRC = 0.
    DELETE ZTSD_GNRET009 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_GNRET009 WHERE
  BUKRS = ZVSD_GNRET009-BUKRS AND
  BRANCH = ZVSD_GNRET009-BRANCH AND
  SHIPTO = ZVSD_GNRET009-SHIPTO AND
  TAXTYP = ZVSD_GNRET009-TAXTYP AND
  ZSUB = ZVSD_GNRET009-ZSUB AND
  ADIANTAMENTO = ZVSD_GNRET009-ADIANTAMENTO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_GNRET009.
    ENDIF.
ZTSD_GNRET009-MANDT =
ZVSD_GNRET009-MANDT .
ZTSD_GNRET009-BUKRS =
ZVSD_GNRET009-BUKRS .
ZTSD_GNRET009-BRANCH =
ZVSD_GNRET009-BRANCH .
ZTSD_GNRET009-SHIPTO =
ZVSD_GNRET009-SHIPTO .
ZTSD_GNRET009-TAXTYP =
ZVSD_GNRET009-TAXTYP .
ZTSD_GNRET009-ZSUB =
ZVSD_GNRET009-ZSUB .
ZTSD_GNRET009-ADIANTAMENTO =
ZVSD_GNRET009-ADIANTAMENTO .
ZTSD_GNRET009-LIFNR =
ZVSD_GNRET009-LIFNR .
ZTSD_GNRET009-HKONT =
ZVSD_GNRET009-HKONT .
ZTSD_GNRET009-HBKID =
ZVSD_GNRET009-HBKID .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_GNRET009 ##WARN_OK.
    ELSE.
    INSERT ZTSD_GNRET009 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_GNRET009-UPD_FLAG,
STATUS_ZVSD_GNRET009-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_GNRET009.
  SELECT SINGLE * FROM ZTSD_GNRET009 WHERE
BUKRS = ZVSD_GNRET009-BUKRS AND
BRANCH = ZVSD_GNRET009-BRANCH AND
SHIPTO = ZVSD_GNRET009-SHIPTO AND
TAXTYP = ZVSD_GNRET009-TAXTYP AND
ZSUB = ZVSD_GNRET009-ZSUB AND
ADIANTAMENTO = ZVSD_GNRET009-ADIANTAMENTO .
ZVSD_GNRET009-MANDT =
ZTSD_GNRET009-MANDT .
ZVSD_GNRET009-BUKRS =
ZTSD_GNRET009-BUKRS .
ZVSD_GNRET009-BRANCH =
ZTSD_GNRET009-BRANCH .
ZVSD_GNRET009-SHIPTO =
ZTSD_GNRET009-SHIPTO .
ZVSD_GNRET009-TAXTYP =
ZTSD_GNRET009-TAXTYP .
ZVSD_GNRET009-ZSUB =
ZTSD_GNRET009-ZSUB .
ZVSD_GNRET009-ADIANTAMENTO =
ZTSD_GNRET009-ADIANTAMENTO .
ZVSD_GNRET009-LIFNR =
ZTSD_GNRET009-LIFNR .
ZVSD_GNRET009-HKONT =
ZTSD_GNRET009-HKONT .
ZVSD_GNRET009-HBKID =
ZTSD_GNRET009-HBKID .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_GNRET009 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_GNRET009-BUKRS TO
ZTSD_GNRET009-BUKRS .
MOVE ZVSD_GNRET009-BRANCH TO
ZTSD_GNRET009-BRANCH .
MOVE ZVSD_GNRET009-SHIPTO TO
ZTSD_GNRET009-SHIPTO .
MOVE ZVSD_GNRET009-TAXTYP TO
ZTSD_GNRET009-TAXTYP .
MOVE ZVSD_GNRET009-ZSUB TO
ZTSD_GNRET009-ZSUB .
MOVE ZVSD_GNRET009-ADIANTAMENTO TO
ZTSD_GNRET009-ADIANTAMENTO .
MOVE ZVSD_GNRET009-MANDT TO
ZTSD_GNRET009-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_GNRET009'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_GNRET009 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_GNRET009'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
