"Name: \PR:SAPLJ1BB\FO:PROCESSING_CHECKS\SE:BEGIN\EI
ENHANCEMENT 0 ZEISD_CHECAR_DUPLIC.
INCLUDE zsdi_check_duplic IF FOUND.
INCLUDE zmmi_escrt_nfe_graoverde IF FOUND.
INCLUDE zmmi_gko_process IF FOUND.
INCLUDE zsdi_check_date_doc IF FOUND.
ENDENHANCEMENT.
