*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_DIR_FIS_ATV................................*
FORM GET_DATA_ZVSD_DIR_FIS_ATV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_DIR_FIS_ATV WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_DIR_FIS_ATV .
ZVSD_DIR_FIS_ATV-CLIENT =
ZTSD_DIR_FIS_ATV-CLIENT .
ZVSD_DIR_FIS_ATV-SHIPFROM =
ZTSD_DIR_FIS_ATV-SHIPFROM .
ZVSD_DIR_FIS_ATV-AUART =
ZTSD_DIR_FIS_ATV-AUART .
ZVSD_DIR_FIS_ATV-J_1BTAXLW1 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW1 .
ZVSD_DIR_FIS_ATV-J_1BTAXLW2 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW2 .
ZVSD_DIR_FIS_ATV-J_1BTAXLW5 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW5 .
ZVSD_DIR_FIS_ATV-J_1BTAXLW4 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW4 .
<VIM_TOTAL_STRUC> = ZVSD_DIR_FIS_ATV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_DIR_FIS_ATV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_DIR_FIS_ATV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_DIR_FIS_ATV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_DIR_FIS_ATV WHERE
  SHIPFROM = ZVSD_DIR_FIS_ATV-SHIPFROM AND
  AUART = ZVSD_DIR_FIS_ATV-AUART .
    IF SY-SUBRC = 0.
    DELETE ZTSD_DIR_FIS_ATV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_DIR_FIS_ATV WHERE
  SHIPFROM = ZVSD_DIR_FIS_ATV-SHIPFROM AND
  AUART = ZVSD_DIR_FIS_ATV-AUART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_DIR_FIS_ATV.
    ENDIF.
ZTSD_DIR_FIS_ATV-CLIENT =
ZVSD_DIR_FIS_ATV-CLIENT .
ZTSD_DIR_FIS_ATV-SHIPFROM =
ZVSD_DIR_FIS_ATV-SHIPFROM .
ZTSD_DIR_FIS_ATV-AUART =
ZVSD_DIR_FIS_ATV-AUART .
ZTSD_DIR_FIS_ATV-J_1BTAXLW1 =
ZVSD_DIR_FIS_ATV-J_1BTAXLW1 .
ZTSD_DIR_FIS_ATV-J_1BTAXLW2 =
ZVSD_DIR_FIS_ATV-J_1BTAXLW2 .
ZTSD_DIR_FIS_ATV-J_1BTAXLW5 =
ZVSD_DIR_FIS_ATV-J_1BTAXLW5 .
ZTSD_DIR_FIS_ATV-J_1BTAXLW4 =
ZVSD_DIR_FIS_ATV-J_1BTAXLW4 .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_DIR_FIS_ATV ##WARN_OK.
    ELSE.
    INSERT ZTSD_DIR_FIS_ATV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_DIR_FIS_ATV-UPD_FLAG,
STATUS_ZVSD_DIR_FIS_ATV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_DIR_FIS_ATV.
  SELECT SINGLE * FROM ZTSD_DIR_FIS_ATV WHERE
SHIPFROM = ZVSD_DIR_FIS_ATV-SHIPFROM AND
AUART = ZVSD_DIR_FIS_ATV-AUART .
ZVSD_DIR_FIS_ATV-CLIENT =
ZTSD_DIR_FIS_ATV-CLIENT .
ZVSD_DIR_FIS_ATV-SHIPFROM =
ZTSD_DIR_FIS_ATV-SHIPFROM .
ZVSD_DIR_FIS_ATV-AUART =
ZTSD_DIR_FIS_ATV-AUART .
ZVSD_DIR_FIS_ATV-J_1BTAXLW1 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW1 .
ZVSD_DIR_FIS_ATV-J_1BTAXLW2 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW2 .
ZVSD_DIR_FIS_ATV-J_1BTAXLW5 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW5 .
ZVSD_DIR_FIS_ATV-J_1BTAXLW4 =
ZTSD_DIR_FIS_ATV-J_1BTAXLW4 .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_DIR_FIS_ATV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_DIR_FIS_ATV-SHIPFROM TO
ZTSD_DIR_FIS_ATV-SHIPFROM .
MOVE ZVSD_DIR_FIS_ATV-AUART TO
ZTSD_DIR_FIS_ATV-AUART .
MOVE ZVSD_DIR_FIS_ATV-CLIENT TO
ZTSD_DIR_FIS_ATV-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_DIR_FIS_ATV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_DIR_FIS_ATV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_DIR_FIS_ATV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
