*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSD_ICMSDIF....................................*
FORM GET_DATA_ZVSD_ICMSDIF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSD_ICMSDIF WHERE
(VIM_WHERETAB) .
    CLEAR ZVSD_ICMSDIF .
ZVSD_ICMSDIF-MANDT =
ZTSD_ICMSDIF-MANDT .
ZVSD_ICMSDIF-UF_EMIS =
ZTSD_ICMSDIF-UF_EMIS .
ZVSD_ICMSDIF-UF_RECE =
ZTSD_ICMSDIF-UF_RECE .
ZVSD_ICMSDIF-MATNR =
ZTSD_ICMSDIF-MATNR .
ZVSD_ICMSDIF-MATKL =
ZTSD_ICMSDIF-MATKL .
ZVSD_ICMSDIF-PORCENTAGEM =
ZTSD_ICMSDIF-PORCENTAGEM .
ZVSD_ICMSDIF-DATE_FROM =
ZTSD_ICMSDIF-DATE_FROM .
ZVSD_ICMSDIF-DATE_TO =
ZTSD_ICMSDIF-DATE_TO .
<VIM_TOTAL_STRUC> = ZVSD_ICMSDIF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSD_ICMSDIF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSD_ICMSDIF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSD_ICMSDIF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_ICMSDIF WHERE
  UF_EMIS = ZVSD_ICMSDIF-UF_EMIS AND
  UF_RECE = ZVSD_ICMSDIF-UF_RECE AND
  MATNR = ZVSD_ICMSDIF-MATNR AND
  MATKL = ZVSD_ICMSDIF-MATKL .
    IF SY-SUBRC = 0.
    DELETE ZTSD_ICMSDIF .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSD_ICMSDIF WHERE
  UF_EMIS = ZVSD_ICMSDIF-UF_EMIS AND
  UF_RECE = ZVSD_ICMSDIF-UF_RECE AND
  MATNR = ZVSD_ICMSDIF-MATNR AND
  MATKL = ZVSD_ICMSDIF-MATKL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSD_ICMSDIF.
    ENDIF.
ZTSD_ICMSDIF-MANDT =
ZVSD_ICMSDIF-MANDT .
ZTSD_ICMSDIF-UF_EMIS =
ZVSD_ICMSDIF-UF_EMIS .
ZTSD_ICMSDIF-UF_RECE =
ZVSD_ICMSDIF-UF_RECE .
ZTSD_ICMSDIF-MATNR =
ZVSD_ICMSDIF-MATNR .
ZTSD_ICMSDIF-MATKL =
ZVSD_ICMSDIF-MATKL .
ZTSD_ICMSDIF-PORCENTAGEM =
ZVSD_ICMSDIF-PORCENTAGEM .
ZTSD_ICMSDIF-DATE_FROM =
ZVSD_ICMSDIF-DATE_FROM .
ZTSD_ICMSDIF-DATE_TO =
ZVSD_ICMSDIF-DATE_TO .
    IF SY-SUBRC = 0.
    UPDATE ZTSD_ICMSDIF ##WARN_OK.
    ELSE.
    INSERT ZTSD_ICMSDIF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSD_ICMSDIF-UPD_FLAG,
STATUS_ZVSD_ICMSDIF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSD_ICMSDIF.
  SELECT SINGLE * FROM ZTSD_ICMSDIF WHERE
UF_EMIS = ZVSD_ICMSDIF-UF_EMIS AND
UF_RECE = ZVSD_ICMSDIF-UF_RECE AND
MATNR = ZVSD_ICMSDIF-MATNR AND
MATKL = ZVSD_ICMSDIF-MATKL .
ZVSD_ICMSDIF-MANDT =
ZTSD_ICMSDIF-MANDT .
ZVSD_ICMSDIF-UF_EMIS =
ZTSD_ICMSDIF-UF_EMIS .
ZVSD_ICMSDIF-UF_RECE =
ZTSD_ICMSDIF-UF_RECE .
ZVSD_ICMSDIF-MATNR =
ZTSD_ICMSDIF-MATNR .
ZVSD_ICMSDIF-MATKL =
ZTSD_ICMSDIF-MATKL .
ZVSD_ICMSDIF-PORCENTAGEM =
ZTSD_ICMSDIF-PORCENTAGEM .
ZVSD_ICMSDIF-DATE_FROM =
ZTSD_ICMSDIF-DATE_FROM .
ZVSD_ICMSDIF-DATE_TO =
ZTSD_ICMSDIF-DATE_TO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSD_ICMSDIF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSD_ICMSDIF-UF_EMIS TO
ZTSD_ICMSDIF-UF_EMIS .
MOVE ZVSD_ICMSDIF-UF_RECE TO
ZTSD_ICMSDIF-UF_RECE .
MOVE ZVSD_ICMSDIF-MATNR TO
ZTSD_ICMSDIF-MATNR .
MOVE ZVSD_ICMSDIF-MATKL TO
ZTSD_ICMSDIF-MATKL .
MOVE ZVSD_ICMSDIF-MANDT TO
ZTSD_ICMSDIF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSD_ICMSDIF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSD_ICMSDIF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSD_ICMSDIF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
