"Name: \TY:CL_CFD_RUNTIME_GUI\ME:GET_DATA_FROM_DATA_ELEMENT\SE:BEGIN\EI
ENHANCEMENT 0 ZEISD_ORDENA_CAMPOS_PERSON.
IF line_exists( ct_gui_data[ gui_context = 'SD_SALESDOC_GUI' ] ).
  SORT ct_gui_data BY time_stamp ASCENDING.
ENDIF.
ENDENHANCEMENT.
